version: '3.3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: dockerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dockerdb
      DB_USERNAME: dockeruser
      DB_PASSWORD: dockerpassword

volumes:
  postgres-data:
